# Generated by Django 4.2.1 on 2023-05-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_student_id_alter_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
