# Generated by Django 4.2.1 on 2023-05-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_remove_attendance_student_remove_attendance_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.student'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='quizzes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.quiz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.branch'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.branch'),
        ),
    ]
