# Generated by Django 4.2.1 on 2023-05-15 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100, message='Please enter a number less than 100'), django.core.validators.MinValueValidator(0, message='Please enter a number above 0')])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.branch')),
                ('subjects', models.ManyToManyField(to='Dashboard.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('guardian_first_name', models.CharField(max_length=50)),
                ('guardian_second_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.branch')),
                ('subjects', models.ManyToManyField(to='Dashboard.subject')),
            ],
        ),
    ]
