# Generated by Django 4.2.1 on 2023-05-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_student_gender_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(to='Dashboard.attendance'),
        ),
    ]
