# Generated by Django 4.2.1 on 2023-05-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attended',
        ),
    ]
