# Generated by Django 4.2.1 on 2023-05-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_alter_attendance_student_alter_attendance_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(to='Dashboard.attendance'),
        ),
    ]
