# Generated by Django 4.2.1 on 2023-05-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_alter_attendance_student_alter_student_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Dashboard.student'),
        ),
        migrations.AddField(
            model_name='branch',
            name='students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Dashboard.student'),
        ),
        migrations.AddField(
            model_name='branch',
            name='teachers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Dashboard.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Dashboard.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Dashboard.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='quizzes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.quiz'),
        ),
    ]
